language: node_js
node_js:
  - 4
  - 6 
  - 7
before_install:
  - npm install -g npm@3
  - npm config set loglevel error
  - npm config -g list -l
  - npm --version
script: npm run-script ci
cache:
  directories:
    - node_modules
notifications:
  flowdock: e3dc17bc8a2c1b3412abe3e5747f8291
